apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hub.fullname" . }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
data:
  SERVICE_PORT: {{ .Values.hub.config.port | quote }}
  SERVICE_HOST: {{ .Values.hub.config.host | quote }}
  SERVICE_ENVIRONMENT: {{ .Values.hub.config.environment | quote }}
  SERVICE_LOG_LEVEL: {{ .Values.hub.config.logLevel | quote }}
