{{- if and .Values.hub.config.openai.enabled .Values.hub.config.openai.apiKey.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hub.fullname" . }}-openai
  labels:
    {{- include "hub.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.hub.config.openai.apiKey.externalSecret.secretStore.name }}
    kind: {{ .Values.hub.config.openai.apiKey.externalSecret.secretStore.kind }}
  target:
    name: {{ include "hub.fullname" . }}-openai
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: {{ .Values.hub.config.openai.apiKey.externalSecret.remoteRef.key }}
      {{- if .Values.hub.config.openai.apiKey.externalSecret.remoteRef.property }}
      property: {{ .Values.hub.config.openai.apiKey.externalSecret.remoteRef.property }}
      {{- end }}
{{- end }}
