{{- if or (and (not .Values.cloudnativepg.enabled) (not .Values.externalDatabase.existingSecret.name) .Values.externalDatabase.password) .Values.hub.config.apiKey.value .Values.hub.config.openai.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub.fullname" . }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.cloudnativepg.enabled) (not .Values.externalDatabase.existingSecret.name) .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.hub.config.apiKey.value }}
  api-key: {{ .Values.hub.config.apiKey.value | b64enc | quote }}
  {{- end }}
  {{- if .Values.hub.config.openai.apiKey.value }}
  openai-api-key: {{ .Values.hub.config.openai.apiKey.value | b64enc | quote }}
  {{- end }}
{{- end }}
